### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by sroehrl** [sroehrl/neoan3-userModel#2]
Need to write test-functions and find a way to facilitate testing outside of a neoan3 context.

Challenge: ideally, models can be tested outside of the context of a neoan3 installation. Suggestions on how to do that would go a long way. 

Any experienced PHPUnit testers want to show me how it's done?

**Comment by LeoVie** [comment]
I'll give it a try. :)

**Comment by sroehrl** [comment]
Perfect. TY

**Comment by LeoVie** [comment]
Hm, unit testing this is quite complicated, as all methods are static.
Is there a chance to transform them into non static methods? This would increase the testability dramatically, as you can mock the dependencies then.
This should get changed in the main project "neoan3", too.

**Comment by sroehrl** [comment]
The static approach was a design decision based on the way transactions are intended to be facilitated and how internal and external libraries are intended to be used. As you correctly identified, this creates a challenge when packages are independently tested.
The versioning/collaboration approach of neoan3 allows for development in context. Traditionally, one would simply create a particular entity (here a model) and develop it within context of the application before packaging it into its own repository (see [publishing](https://github.com/sroehrl/neoan3-cli#publish) ). 

Now, as soon as these entities are their own package (like this one), any testing based on the context faces two challenges:

- the challenge of missing, hard to mock context (like you probably experienced e.g. by missing the index model)
- the challenge of potentially outdated mock data as related classes/entities are versioned and developed independently.

I am therefore super open to ideas, but this particular one is not an option. The reason why this issue uses the wording "Suggestions on how to do that would go a long way" is exactly due to this challenge, as a good approach would introduce a repeatable method. So if you have grand ideas (like generating a general test wrapper and loading dependencies via require dev), I'd be highly interested.

**Comment by LeoVie** [comment]
Hi, I'm unassigning me from this issue, but I'll keep an eye on it, as I'm interested in a solution.

**Comment by sroehrl** [comment]
Closing this issue (finally) due to neoan3 now offering providers and injections
